version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      target: release  # Target the release stage of the Dockerfile
    ports:
      - "42069:80"  # Map port 80 of the container to port 42069 of the host
    depends_on:
      - middleware

  middleware:
    build: ./middleware
    ports:
      - "5001:5000"
    depends_on:
      - database

  database:
    container_name: db
    build: ./database
    restart: always
    ports:
     - "1434:1435" 
  